# Creating Arrays

In [1]:
import numpy as np

In [ ]:
#Arrays can be created from lists

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11,22,33,44]

In [12]:
my_lists = [my_list1, my_list2]  #make a list of lists

In [ ]:
#can make multidimensional array (matrix) using that composite list

In [13]:
my_array2 = np.array(my_lists)
my_array2
#every small list in the list of lists becomes the rows of the matrix

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
my_array2.shape  #shows dimension of array: 2 by 4 (2 rows, 4 columns)

(2, 4)

In [15]:
my_array2.dtype

dtype('int32')

In [17]:
np.zeros(5)  #special arrays: array of zeroes, and dimension wanted
#here, 1 by 5

array([0., 0., 0., 0., 0.])

In [18]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array.dtype #Note the variable type and decimal point

dtype('float64')

In [21]:
np.ones([5,5]) #special array: array of ones, and dimension desired
#here, 5 by 5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty(5) #special array: empty array, same as array of zeros

array([2.18559879e-316, 1.60216183e-306, 7.56602523e-307, 1.11258446e-306,
       4.45063578e-308])

np.eye(5) #speical array: the identity array, square matrix only

In [28]:
#commonly used method: arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(5,50,2)   
#generate a 1D array with input start, end, stepsize

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [34]:
np.array([np.arange(0,5),np.arange(6,11)])

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

# Arrays and Scalars operation/interaction

In [35]:
import numpy as np

In [36]:
5/2

2.5

In [38]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [39]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [41]:
arr1*arr1    #scalar multiplication of arrays (position-by-position)

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [42]:
arr1 - arr1 #scalar subtration

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
1 / arr1 #scalar onto arrays

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [44]:
arr1 ** 3  #exponents (power of 3)

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

# Indexing Arrays

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)   #construct one dimensional array of 11 elements, starting at 0, up to and not including 11

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0] #remember python indexing starts at 0.

0

In [6]:
arr[2]

2

In [7]:
arr[1:5]  #to grab a value at a certain range, exclusive of the last value

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[0:5] =  100  #can also set all the values in that range equal to something

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#array slicing
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99  #can change all the elements in that array using only colon in indexing
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
#At this point, note the original array
#in Numpy, editing slices of an array WILL affect the original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
#If want a copy, have to be explicit
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
#indexing 2D arrays
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[1]   #indexing rows by using indexing a number to the 2D array, here, indexing 2nd row

array([20, 25, 30])

In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [26]:
arr_2d[1][0]  #to index a specific value, index the row first, then index again for which value of the row. 
#[row][column] selection
#here, it's indexing 2nd row, 1st value = 20

20

In [28]:
#2d array slicing
arr_2d[:2,1:]
#array[everything until 3rd row index, 2nd column index to everything after]
#indexed the upper right 2x2 matrix of the bigger matrix

array([[10, 15],
       [25, 30]])

In [29]:
arr_2d[2]  #bottom row

array([35, 40, 45])

In [37]:
#fancy indexing

#set up 10x10 zeroes array, note all floats
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
arr_length = arr2d.shape[1]
arr_length
#the array has a length of 10

int

In [40]:
for i in range(arr_length):
    arr2d[i]=1
    
#employing for loop to modify the array, changing the ith element in the array the value 1
#each element selected is a row, so change each row to 1's

In [44]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
#slight modification to the loop yields:
for i in range(arr_length):
    arr2d[i]=i

#change the first row to 0s, 2nd row to 1s, 3rd row to 2s... so on
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [46]:
arr2d[[2,4,6,8]] #fancy indexing: only index certain rows based on row index number

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [50]:
arr2d[[0,9]]  #can do this in any order, hence the name "fancy"

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [51]:
arr2d[[7,4,2]]

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

# Array Transposition

In [52]:
import numpy as np

In [54]:
arr = np.arange(50).reshape((10,5))   #arange function, generate array with 50 values, which is 10 by 5 in dimension
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [56]:
#to tranpose this matrix, pretty easy, use .T method
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [57]:
#dot product of arrays (in this case, the transposed array to the original)
#actual array multiplication
np.dot(arr.T, arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [63]:
#Note can also make 3D matrices, but it is not used much
arr3d = np.arange(50).reshape((5,5,2))  #generate array with 50 values, dimensions 5 by (5 by 2) (5 slices of 5x2 matrices)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [61]:
#can transpose the 3D matrix, but have to specify axis of transpose, by default it will be a complete flip (5x5x2 to 2x5x5)
arr3d.transpose()

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

In [64]:
arr3d.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [67]:
arr = np.array([[1,2,3]]) #note double brackets to indicate 2 possible dimensions
arr

array([[1, 2, 3]])

In [68]:
arr.swapaxes(0,1)  #changes the row array to a column array.

array([[1],
       [2],
       [3]])

# Universal Array Functions

In [69]:
import numpy as np

In [70]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#universal functions = basic functions you can apply to an array

In [71]:
#square-root element-wise
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [72]:
#take the exponential of every element in the array (e to the x)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [75]:

A = np.random.randn(10)  #normal distribution of random numbers array

A

array([ 0.26393496,  0.42324128,  1.11115374, -0.98708512, -0.5714939 ,
        0.16557807, -1.02213659, -0.06292549, -0.27095244,  0.61259753])

In [76]:
B = np.random.randn(10)
B

array([ 0.93780719, -1.14690779, -0.86118211,  1.01798466, -1.47159838,
        0.35407957,  0.70420704,  2.15979986, -0.3819589 ,  1.23205872])

In [77]:
#Binary functions (require 2 arrays)

#element-wise addition between two arrays
np.add(A,B)

array([ 1.20174215, -0.7236665 ,  0.24997164,  0.03089954, -2.04309228,
        0.51965764, -0.31792955,  2.09687437, -0.65291133,  1.84465625])

In [78]:
#find the maximums between the two arrays (comparing values at each index)
#minimum is the same 
np.maximum(A,B)

array([ 0.93780719,  0.42324128,  1.11115374,  1.01798466, -0.5714939 ,
        0.35407957,  0.70420704,  2.15979986, -0.27095244,  1.23205872])

In [79]:
#full documentation/list of all the universal functions (mostly mathematical related)
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"


True