# Creating Arrays

In [1]:
import numpy as np

In [ ]:
#Arrays can be created from lists

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11,22,33,44]

In [12]:
my_lists = [my_list1, my_list2]  #make a list of lists

In [ ]:
#can make multidimensional array (matrix) using that composite list

In [13]:
my_array2 = np.array(my_lists)
my_array2
#every small list in the list of lists becomes the rows of the matrix

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
my_array2.shape  #shows dimension of array: 2 by 4 (2 rows, 4 columns)

(2, 4)

In [15]:
my_array2.dtype

dtype('int32')

In [17]:
np.zeros(5)  #special arrays: array of zeroes, and dimension wanted
#here, 1 by 5

array([0., 0., 0., 0., 0.])

In [18]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array.dtype #Note the variable type and decimal point

dtype('float64')

In [21]:
np.ones([5,5]) #special array: array of ones, and dimension desired
#here, 5 by 5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty(5) #special array: empty array, same as array of zeros

array([2.18559879e-316, 1.60216183e-306, 7.56602523e-307, 1.11258446e-306,
       4.45063578e-308])

np.eye(5) #speical array: the identity array, square matrix only

In [28]:
#commonly used method: arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(5,50,2)   
#generate a 1D array with input start, end, stepsize

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [34]:
np.array([np.arange(0,5),np.arange(6,11)])

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

# Arrays and Scalars operation/interaction

In [35]:
import numpy as np

In [36]:
5/2

2.5

In [38]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [39]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [41]:
arr1*arr1    #scalar multiplication of arrays (position-by-position)

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [42]:
arr1 - arr1 #scalar subtration

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
1 / arr1 #scalar onto arrays

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [44]:
arr1 ** 3  #exponents (power of 3)

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)